### PR TITLE
Use the `optimade` container image as a service

### LINKED ISSUE #106: Docker-compose references should be removed
See [this CI run](https://github.com/Materials-Consortia/optimade-validator-action/actions/runs/2332022611)

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #106 

Instead of running docker-compose in CI.

### CODE REVIEW

**Comment by CasperWA** [comment]
Hmm, I get [the same error](https://github.com/Materials-Consortia/optimade-validator-action/runs/6455203620?check_suite_focus=true#step:4:304) locally. It's strange that it prints `localhost:5000` instead of `gh_actions_host:3213`. Is this an error in the validator in OPT?

**Comment by CasperWA** [comment]
> Or is it perhaps due to the set `OPTIMADE_BASE_URL`?

Yup - that's it.

**Review by ml-evs — APPROVED** [review]
Nice and clean :)

**Comment by CasperWA** [comment]
> I guess my only comment is actually that the services can be moved to the top-level right to be used by all workflows, I think? Not something to worry about, given auto-merge is about to happen 🙃

I don't think that's possible. Services are job-specific as far as I know, so this is the main way to do this.

**Pull request merged**
