### PR TITLE
[BLOCKING] Clone optimade-python-tools and run docker-compose

### LINKED ISSUE #2: Fix CI tests
In this fresh state, the CI tests for the validator is not working, since it was utilizing the docker in the `optimade-python-tools` repository.

A workaround must be put in place for the CI tests specifically.

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #2 

The initial work-around here is to `git clone` the `optimade-python-repository` into the temporary GH Actions server and - without installing anything - run the `docker-compose.yml` file found in the repository root of `optimade-python-repository`.

### CODE REVIEW

**Comment by shyamd** [comment]
So, the CI tests might be ill-conditioned here. The CI shouldn't be testing the optimade-server but the action. Since the action tests the optimade-server, we don't actually want to test the server in the CI. Rather we should just be testing to ensure the action is running the right command and properly failing/succeeding depending on the output of that command.

**Comment by CasperWA** [comment]
> So, the CI tests might be ill-conditioned here. The CI shouldn't be testing the optimade-server but the action. Since the action tests the optimade-server, we don't actually want to test the server in the CI. Rather we should just be testing to ensure the action is running the right command and properly failing/succeeding depending on the output of that command.

Agreed. It's a bit wishy-washy where to draw the line at the moment though. But I have been introducing tests of `entrypoint.sh` via BATS in #4. Maybe that's more sensible in the end? Although I do think we should also have at least the two first tests from the CI or something similar to it to test that the `optimade_validator` will indeed be invoked correctly.

**Comment by shyamd** [comment]
Yup. I like the BATS testing. One viable option would be to make a dummy `optimade-validator` in the right place and ensure it gets called.

**Comment by CasperWA** [comment]
> Yup. I like the BATS testing. One viable option would be to make a dummy `optimade-validator` in the right place and ensure it gets called.

Very nice idea. It just sets an environment variable, outputs something or other 👍

**Comment by CasperWA** [comment]
So what do you say to get this merged as a temporary solution, opening the possibility of getting the other open PRs merged, create an issue to convert all CI to BATS testing (based on the work I started in #4) and then finally release v1 - the CI testing shouldn't hinder the release I think?

**Comment by CasperWA** [comment]
> Missed the huge blocking sign when I reviewed the other PR first X)

No worries - but what do you think about [this comment](https://github.com/Materials-Consortia/optimade-validator-action/pull/3#issuecomment-598302816)?

**Comment by shyamd** [comment]
I agree, let's merge and then update.

**Pull request merged**
