### PR TITLE
Fix `as type` implementation

### LINKED ISSUE #56: as_type seems to be used incorrectly
In the test of `as type`, it seems we're passing the root base URL, which shouldn't be the case, right? We should pass in a full URL to a relevant single endpoint that should be validated using the passed type?

I.e., instead of testing:
```sh
TEST_BASE_RUN_VALIDATOR="optimade-validator $( for i in {1..${INPUT_VERBOSITY}}; do echo '-v '; done; )--as-type ${VALID_AS_TYPE_VALUE} ${INPUT_PROTOCOL}://${INPUT_DOMAIN}${INPUT_PATH}"
```
We should be testing:
```sh
TEST_BASE_RUN_VALIDATOR="optimade-validator $( for i in {1..${INPUT_VERBOSITY}}; do echo '-v '; done; )--as-type ${VALID_AS_TYPE_VALUE} ${INPUT_PROTOCOL}://${INPUT_DOMAIN}${INPUT_PATH}v1/structures/${VALID_STRUCTURE_ID}"
```
Where `VALID_STRUCTURE_ID` is a variable that ensures we are testing a valid structure ID.
Note, `VALID_AS_TYPE_VALUE=structure` here.

Essentially, the action should avoid adding versioned parts to the URL and simply use the passed `path` parameter as is.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #56.

If `as type` is supplied it is understood that the domain+path constitutes the complete URL to be tested.
Hence, only a single validation will be run, and the parameters `all versioned paths` and `validate unversioned path` have no meaning and will be ignored.
This means `as type` take precedence, which is what I would expect.

Possibly add:
- [x] Extend README with the internal precedence of parameters.

### CODE REVIEW

**Comment by CasperWA** [comment]
It seems to me like there's an issue with the validator when using the `--as-type` parameter: [CI running with verbosity 2](https://github.com/Materials-Consortia/optimade-validator-action/runs/1863226801?check_suite_focus=true#step:11:81).

**Comment by CasperWA** [comment]
It looks like the validator is running fine, but then either doesn't set `valid` to `True` or another issue presents itself. It also doesn't call `print_summary()` before returning, but I wouldn't think that that would matter?

**Comment by CasperWA** [comment]
Hmm, I tried it locally, and the return code is `0`, so I'm not completely sure what's going on here.

**Comment by CasperWA** [comment]
I found the reason for the action to exit with a non-zero code.
In Bash, if a negative check is done, and it's not true, the last pipestatus is non-zero. In order to ensure a "correct" pipestatus and
script exit code, an else clause can be added with a "pass" statement, in the form of a colon (`:`).

However, this created some issues with the exit code to be reported in `entrypoint.sh`. Instead, I have now moved the `as type` validator run to a later point, which should ensure the correct exit code is always reported, and there's no confusion concerning if/else tests affecting the exit code through pipestatus.

**Comment by CasperWA** [comment]
Note, currently I'm using a special branch of the `optimade` package for the `as type` CI test. A PR should be opened and merged before this PR can be merged.

**Comment by CasperWA** [comment]
@ml-evs ready for review

**Review by ml-evs — APPROVED** [review]
LGTM!

**Pull request merged**
